- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none  
  notify:
        - reload NetworkManager

- name: deploy resolv.conf template
  template:  
    src: "templates/{{ dns_file }}.j2"      
    dest: /etc/resolv.conf